### PR TITLE
Android: UI Improvements

### PR DESCRIPTION
**Pull request by dosiecki**
This change goes after a good number of small UI tweaks for which we've had open issues.  In particular:

* added fleurons to completed story lists (#903)
* fixed list background colours (per comments in #903)
* adjustable font sizes for story lists (#861)
* forgot-password workflow (#900)
* minor fixes to focus pathing (#837)

I also did a pass over some mismatched or slightly-off theme colours and made them more closely match the iOS UI or the web UI or both (where possible), vaguely guided by the Android UX guidelines (again, where possible).  I would say that about 75% of the app now has a nice, clean, consistent palate; I'll be finishing off the remaining artifacts in the next pull.

Finally, a handfull of bux fixes.  Also bit the bullet and cut off update support for the oldest ~4% of Android devices out there that were costing us a ton of time in testing and support.

### CODE REVIEW

**Comment by samuelclay** [comment]
Gonna push this out as a beta.

**Comment by samuelclay** [comment]
There is something bizarre happening, where when I go into a feed, stories from other feeds show up and don't go away.

**Comment by dosiecki** [comment]
Is your device under duress of any sort or does the problem go away after letting it sit for a moment? Try swiping the app closed and seeing if that changes things. Also, device / platform version info?

**Comment by dosiecki** [comment]
Went back and confirmed that nothing about sync has changed since the last release, so if there are any issues, they aren't regressions.  One other diagnostic in addition to the usual feedbacklink data - was your Android device turned on for the first time in a while when the test was performed?

**Comment by samuelclay** [comment]
Yes it was. I unplugged it a couple weeks ago and forgot to charge it. So it was just turning back on, although I let it charge for an hour.

**Comment by samuelclay** [comment]
Samsung Galaxy S5

**Pull request merged**
