### PR TITLE
Android: Fix crash in #679.

### PR DESCRIPTION
**Pull request by dosiecki**
Good catch. Ready for more testing.

### CODE REVIEW

**Comment by samuelclay** [comment]
I've gone home for the day with a headache but I'll get this launched tomorrow.

**Comment by samuelclay** [comment]
Deployed as v4.2.3b4.

**Comment by dosiecki** [comment]
Three days and a little over 300 installs in beta and no crashes reported.

If you and @manderson23 have tested to satisfaction, I'd suggest we consider pushing this up to Prod, as it has the one nasty bugfix in it.

**Comment by samuelclay** [comment]
I'm going to wait until Monday to do so, but will then. I'm on vacation in a week, but that should give us 5 days to catch anything should something arise.

**Comment by manderson23** [comment]
Everything fine for me.

**Pull request merged**
