### PR TITLE
Android: Social, Social, Social

### PR DESCRIPTION
**Pull request by dosiecki**
This patch not only implements the new reply-to-share-without-comment UI, it also fixes a bunch of old bugs related to social (initially triaged in #643), including but not limited to:

* Broken button labels for already-shared stories
* Inconsistent use of "share" vs. platform "send to"
* New comments did not always appear until leaving reading view and performing full refresh
* New comment replies did not always appear until leaving reading view and performing full refresh
* Friend comments did not appear if public comments were present and enabled
* Shares could not be performed offline
* Replies could not be performed offline
* Creation and removal of favourites could not be performed offline
* Comments and replies on stories read via Global Shared Stories leaked into storage
* All comment, reply, and favourite actions had long UI lag
* All comment, reply, and favourite actions had massive memory churn
* Replies other than first reply on a comment never showed
* Un-shared stories never disappeared from a user's share list

Additional improvements and bugfixes:

* Code cleanup via use of Butterknife to bind views and inject listeners
* Fixed unread search order
* Improved instrumentation of network latency
* Removal of orphaned resources
* Crash fixes
* Fixed bleeding of sync metadata after account switch (would keep downloading stories/images for old account)

Ready for Beta!

### CODE REVIEW

**Comment by samuelclay** [comment]
Will release as v4.3.0b3. I think we keep skipping versions, so I want to keep it consistent.

**Comment by samuelclay** [comment]
What else did we have wrapped up in 4.3.0? I'm going to write release notes.

**Comment by dosiecki** [comment]
Looking at the commit logs:

* Memory use reduction
* "Read Stories" view
* Modern http lib
* Many bugfixes

**Comment by samuelclay** [comment]
Nice, this is a great release.

**Comment by samuelclay** [comment]
I uninstalled and I'm still getting a crash on startup. 

```
06-05 11:48:21.933    7481-7481/com.newsblur E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.newsblur, PID: 7481
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.newsblur/com.newsblur.activity.Login}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setOnEditorActionListener(android.widget.TextView$OnEditorActionListener)' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setOnEditorActionListener(android.widget.TextView$OnEditorActionListener)' on a null object reference
            at com.newsblur.fragment.LoginRegisterFragment.onCreateView(LoginRegisterFragment.java:41)
            at android.app.Fragment.performCreateView(Fragment.java:2053)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.app.BackStackRecord.run(BackStackRecord.java:834)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
            at android.app.Activity.performStart(Activity.java:6005)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by dosiecki** [comment]
Device and os version?

**Comment by dosiecki** [comment]
Also, uninstall and try this one, just to see if builds are going differently:

https://github.com/dosiecki/dosieckihome/blob/master/NewsBlur-debug.apk?raw=true

**Comment by samuelclay** [comment]
Happened on both 5.0 and 5.1. I'd rather not side-load an APK. Any idea on that error?

**Comment by dosiecki** [comment]
I think your build environment is over-stripping classes.  Using AndroidStuidio?

**Comment by samuelclay** [comment]
Yep.

**Comment by samuelclay** [comment]
I've tried a clean rebuild and uninstalling repeatedly. Still getting a crash on boot, and now logcat doesn't even show any output (no filter).

**Comment by dosiecki** [comment]
Yeah, confirmed that AndroidStuido is botching the build.  Trying to figure out what it is up to that the raw tools aren't.

**Comment by samuelclay** [comment]
Released v4.3.0 to production.

**Comment by dosiecki** [comment]
Looking pretty good so far.  Have already patched few little bugs that were missed in Beta, will let it soak for another few hours and send along a PR.  (if only we had more active Beta users!)

**Pull request merged**
