### PR TITLE
Android: Efficiency and Bugfixes

### PR DESCRIPTION
**Pull request by dosiecki**
This patch primarily goes after the issues identified in #723.  CPU usage, battery usage, memory churn, and storage usage have all been reduced somewhat.  In cases when the API is unreachable, background CPU and battery usage have been even further reduced.  More importantly, the included design changes will make it much easier in the future to keep reducing CPU and memory overhead.

Also cleaned up a good deal of legacy code and resources and fixed some lint.

Finally, squashed a few spare issues that were identified in the last few weeks.

I anticipate a few more tweaks before we can finally push all this new stuff all the way to Prod, but I think this is a great checkpoint to send to Beta.

There may be a few minor visual changes on some devices as a result of the optimisations.  If any of them are problematic enough to be of worry, feel free to open a new issue and I will see what work-arounds I can find.

### CODE REVIEW

**Comment by manderson23** [comment]
Could the UI be getting stuck showing "Catching up reading actions"? It seems to be spending a lot more time showing that overlay (2 mins+). Even sometimes after navigating into a feed and straight back out.

**Comment by dosiecki** [comment]
Only if you are experiencing network issues or have a stuck request. Logs
should be informative.

**Comment by manderson23** [comment]
I also seem to be getting error messages showing in toasts regularly when marking older/newer as read. Though the actions seem to be successful.

**Comment by dosiecki** [comment]
Logs?

**Comment by manderson23** [comment]
I'll try and catch it.

**Comment by dosiecki** [comment]
One thing I fixed was API->user messaging.  It used to be that all API calls failed silently, even if the errors should have been pushed to the user. (the classic example is trying to unmark a story older than 30 days)  There in one known edge case where the API returns an error message that is not meant to be shown, but there could certain be others.  The logs will explain exactly what fields and values triggered the condition.

**Comment by samuelclay** [comment]
Which call is that? I'd be happy to change it to what we do show the user. Alternatively, feel free to submit a PR in the python code if it's a text change.

**Comment by dosiecki** [comment]
I had recalled that `/reader/delete_feed` returned an error message even on success that was something we had to filter, but maybe that did eventually get fixed?

Basically, if an API response has a `message` (scalar) or `errors` (array) field populated, that message will be displayed to the user.

**Comment by manderson23** [comment]
I think delete feed got fixed at some point.

**Pull request merged**
