### PR TITLE
Android: Bugfixes and Speed

### PR DESCRIPTION
**Pull request by dosiecki**
Big round of bugfixes, speed tweaks, and cruft cleanup.  The old legacy DB is finally gone and we are 100% on the raw sqlite driver. Patched a  bug that will free up GB worth of data on some devices.  Made DB auto-rebuilds more reliable and less impactful to the UI.

Lots of changes here, would recommend at least a few days in Beta.

### CODE REVIEW

**Comment by dosiecki** [comment]
Oh, and as with all patches, don't forget to bump your version strings!

**Comment by samuelclay** [comment]
Will do. This is working great. Fast and accurate. Now we just gotta fix #637. Should be an easy fix, as you just need to use the folder's total unread count, not the count of stories loaded.

**Comment by samuelclay** [comment]
Should I be disabling logging somehow?

**Comment by dosiecki** [comment]
> Should I be disabling logging somehow?

Nope, already done. (you can always check the top few constants in AppConstants)

**Pull request merged**
