### PR TITLE
Android: Second Notifications Alpha

### PR DESCRIPTION
**Pull request by dosiecki**
As described in #966, another incremental pass at building Android support for notifications.

### CODE REVIEW

**Comment by dosiecki** [comment]
Just a heads-up, I am already tracking down one rare-ish bug where if you tap into two stories from notifications too quickly, they might lag until you rotate your device.  Working on a workaround for the next round of fixes.

**Comment by samuelclay** [comment]
Ok, it's looking good. I did get 5 notifications as I loaded the app, which is a weird experience as I was in the app already. I think that won't be a problem since the app updates itself in the background.

By the way, I keep having to turn on Download Stories. Can we ensure that this option is checked by default?

Also, what's the story with background updates. Is there a preference for this anywhere? On iOS, background updates are unreliable and infrequent.

**Comment by dosiecki** [comment]
> which is a weird experience as I was in the app already.

Should notifications not pop if the app is in the foreground?  I could easily change this behaviour, but I figured it was still appropriate for them to show, since you might have thousands of stories on screen but still want to be able to jump to the notification-enabled ones with a single tap. 

> I keep having to turn on Download Stories. Can we ensure that this option is checked by default?

I would love to default this to enabled, totally unrelated to Notifications.  It makes the UX so much smoother and honestly has few ill side effects.  Most users seem to enable it, too, from what I have seen.

> Also, what's the story with background updates. Is there a preference for this anywhere?

As it turns out, background updates are the *only* way the app communicates with the servers; there is essentially no such thing as a foreground sync.  This is a pretty common Android design pattern.  The UI uses a pair of event busses to communicate with the background service to do real-time stuff.  If the user disables background story sync (or if the network is not of the authorized type), the background sync just stops a little bit earlier.

**Comment by samuelclay** [comment]
Yeah, let's turn off notifications for stories that come in while in the app. Notifications are intended as a background notification.

**Comment by dosiecki** [comment]
> Yeah, let's turn off notifications for stories that come in while in the app. Notifications are intended as a background notification.

Finally having found a few use cases for notifications and using them for a few days, this goes rather counter to their value for me; if I spend an hour reading in one feed, I absolutely want to be notified if I get a story of interest in a different feed.

Is it just the sudden pop of notifications that you got when first enabling them that is the problem, or am I an outlier that I want to see notifications even if I am buried elsewhere in the app?

**Comment by samuelclay** [comment]
I think it's jarring to have notifications, which are meant for you to see when you are elsewhere on your phone (in another app) or rolled up when you return to your phone, pop up when you're initially loading your feeds.

**Comment by samuelclay** [comment]
I'm fine with it though, I just wish the stories would come in as push notifications and not when you loaded the feeds.

I do have an issue with only 1 feed coming through...


screen shot 2017-02-17 at feb 17 1 45 21 pm

**Pull request merged**
