### PR TITLE
Android: Bugfixes, UI micro-Kaizen, Local Feed Search 

### PR DESCRIPTION
**Pull request by dosiecki**
Bugfixes:
* fix crash on trying to interact with muted feeds
* fix crash on malformed stories objects
* fix intent looping when opening stories proxied by feedburner
* fix author text disappearing after training interactions

UI Tweaks:
* add the icon that indicates a shared story in story lists
* highlight title text that impacted intel training disposition
* quick theme switching without going to prefs

Also added a feature I've been wanting for years: the ability to very quickly search my subscribed feeds from right on the feed list.

And, of course, a number of other smaller bug fixes, refactors, typo fixes, and general cleanup.

### CODE REVIEW

**Comment by samuelclay** [comment]
Looks like there's an issue with title highlighting...

**Comment by dosiecki** [comment]
On 10 October 2017 21:00:09 GMT-07:00, Samuel Clay <notifications@github.com> wrote:
>Looks like there's an issue with title highlighting...
>
>

Ah, excellent, this has a lot of edge cases and my use of training is pretty limited. Can you list the classifiers for that feed? (or repro on the shared test account?)

**Comment by samuelclay** [comment]
It's the [Sponsor] and I've seen it in three feeds know: kottke, gothamist, and DF.

**Comment by samuelclay** [comment]
By the way, add the Theme menu to the story list and story detail views. That's a more likely place to switch themes.

**Comment by dosiecki** [comment]
> Looks like there's an issue with title highlighting

Fixed.

> By the way, add the Theme menu to the story list and story detail views. That's a more likely place to switch themes

Ah, the only time I switch themes is when first starting the app after a few hours (and the sun has gone down/up) so left the deeper activities' menus uncluttered.  Will add it as requested, though.

**Pull request merged**
