### PR TITLE
Android: Make reading font dialog sticky

### PR DESCRIPTION
**Pull request by manderson23**
As requested in #1016

### CODE REVIEW

**Comment by samuelclay** [comment]
Thanks!

**Comment by samuelclay** [comment]
I don't think this is related to this commit, but I'm getting a crash when loading kottke.org:

```
05-08 18:02:32.305 18049-18049/com.newsblur E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.newsblur, PID: 18049
                                                              java.lang.NumberFormatException: Invalid long: "#d3a8a3"
                                                                  at java.lang.Long.invalidLong(Long.java:124)
                                                                  at java.lang.Long.parse(Long.java:363)
                                                                  at java.lang.Long.parseLong(Long.java:353)
                                                                  at android.graphics.Color.parseColor(Color.java:221)
                                                                  at com.newsblur.database.StoryItemsAdapter.bindView(StoryItemsAdapter.java:129)
                                                                  at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
                                                                  at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
                                                                  at android.widget.AbsListView.obtainView(AbsListView.java:2929)
                                                                  at android.widget.ListView.makeAndAddView(ListView.java:1945)
                                                                  at android.widget.ListView.fillDown(ListView.java:719)
                                                                  at android.widget.ListView.fillSpecific(ListView.java:1391)
                                                                  at android.widget.ListView.layoutChildren(ListView.java:1712)
                                                                  at android.widget.AbsListView.onLayout(AbsListView.java:2723)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                  at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1731)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                  at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by manderson23** [comment]
Looking at the implementation of android.graphics.Color.parseColor are there two # in the Color instead of one? e.g. ##d3a8a3

**Comment by dosiecki** [comment]
That code hasn't changed in almost a year.  Has something on the backend changed?  Last I checked, the API vends "rrggbb" format, which though it lacks the leading #, has generally been supported.  If you find a device that doesn't support it, we'll probably need to start parsing them by hand for compat.

**Comment by samuelclay** [comment]
Well I can no longer reproduce it, so consider it closed.

**Comment by dosiecki** [comment]
Got the color crash myself today, and fixed the root cause.

**Pull request merged**
