### PR TITLE
Add Android 8.0 notification requirements

### PR DESCRIPTION
**Pull request by caleb-allen**
This creates a Notification Channel which is required on 26+ to display notifications

It also uses the compatibility notification library

Related to #1178

### CODE REVIEW

**Comment by samuelclay** [comment]
I'll deploy this as 9.0.1 right now.

**Comment by samuelclay** [comment]
Any other 9.0 crashes or bugs you'd like me to wait for?

**Comment by caleb-allen** [comment]
Go ahead and push, I'm working on the missing feeds but it probably won't be done today

**Comment by samuelclay** [comment]
Ahh yes, I'll wait for that then.

**Pull request merged**
