### PR TITLE
Android: Bugfixes and Feed List UI Update

### PR DESCRIPTION
**Pull request by dosiecki**
Big round of tweaks to get the Android UI in step with the newsblur.com UI, including #178, #180, #183, and #184.  I still need to do some tweaking (especially of the image resources), but wanted to get this out to Beta as early as possible to see how it works for folks.

Also included a few noncritical bugfixes.

### CODE REVIEW

**Comment by samuelclay** [comment]
Getting a crash when going into and back out of interactions/activity view.

**Comment by samuelclay** [comment]
Tapping on your profile photo should open your profile page. Works like this on iOS, although not the web.

**Comment by samuelclay** [comment]
By the way, this looks awesome and I'm so excited this is going to be released soon.

**Comment by samuelclay** [comment]
Can we remove that ~10 pixel white border at the top of the story titles list? It's leftover from the loading indicator, but I'd like to collapse that space when it's done.

**Comment by samuelclay** [comment]
That's all I've got. Next we should fix the Add Site dialog to include a folder destination and autocomplete-as-you-type. Thanks!

**Comment by manderson23** [comment]
Does the menu still need to include Add new feed and Profile items since there are now separate buttons?

**Comment by manderson23** [comment]
On the Main view I see "You have no unread stories" but a blurblog shows 8 unreads. Are unreads on blurblogs deliberately  not counted?

**Comment by dosiecki** [comment]
> Getting a crash when going into and back out of interactions/activity view.

Definitely send these along or report if installed via the market.  I fully expect some tweaks as we test changes this big on the ~100 platforms we support.

> Tapping on your profile photo should open your profile page. Works like this on iOS, although not the web.

Will do.

> Can we remove that ~10 pixel white border at the top of the story titles list? It's leftover from the loading indicator, but I'd like to collapse that space when it's done

Will see if I can rearrange some layers and get rid of it.

> Does the menu still need to include Add new feed and Profile items since there are now separate buttons?

There is about a 50-50 split on whether action buttons should have text-only conterparts for accessibility reasons.  I generally leave them in unless menu space is becoming constrained.

> On the Main view I see "You have no unread stories" but a blurblog shows 8 unreads. Are unreads on blurblogs deliberately not counted?

Good catch.  I need to check how social is wired into the explainer.

**Pull request merged**
