### PR TITLE
Android: 4.3.0 Bugfixes

### PR DESCRIPTION
**Pull request by dosiecki**
Fixing the handfull of crashes we've logged since the launch of 4.3.0 as well as the busted `login_as` feature.

None of these are very common (hence how they got through Beta), so a quick soak in Beta of the fixes is acceptable.

### CODE REVIEW

**Comment by samuelclay** [comment]
Oh man, sorry I just made #708. I assume this closes it. :+1:

**Comment by dosiecki** [comment]
Any blockers on getting this to Beta?  These crashes are trigging at a very low, but steady rate in Prod.  Happy to help if anything is in the way.

**Comment by samuelclay** [comment]
Pushed to beta as 4.3.1b1.

**Comment by dosiecki** [comment]
Awesome.  Keeping an eye on this, will give a go/nogo by Friday AM.

**Comment by dosiecki** [comment]
Let this go for a few extra days since our beta install rate has fallen again, but so far we haven't seen a single crash.  I am now satisfied that 4.3.1b1 is ready to be promoted, unless anyone has had issue with it.

**Pull request merged**
