### PR TITLE
First pass at iOS keyboard support (#826).

### PR DESCRIPTION
**Pull request by nriley**

### CODE REVIEW

**Comment by samuelclay** [comment]
This is very well done. Thanks @nriley!

**Comment by samuelclay** [comment]
This is for issue #826.

**Comment by samuelclay** [comment]
Hey, can you base this on the 5.1 branch? It'll take a few conflicts to get merged, but this is part of the 5.1 release.

**Comment by nriley** [comment]
Tried to merge tonight but git hates me.  The conflicts so far look pretty minimal.  Will try again later this week.

**Comment by nriley** [comment]
OK, thanks to magit, got the merge done (https://github.com/nriley/NewsBlur/tree/ios-keyboard) but there are some bugs related to the changes in popover support.  I've reported them in #816 and either @Dejal or I can hopefully get them worked out.

**Comment by nriley** [comment]
Should be ready to merge now.

**Comment by nriley** [comment]
Realized the pull request is still reflecting master. Let me close this one and create one explicitly for 5.1.

**Pull request closed without merging**
