### PR TITLE
Android: Search and Bugfixes

### PR DESCRIPTION
**Pull request by dosiecki**
Implements #745.  Also fixes a number of bugs in the current release.  

Good spot for a Beta.  Though most of the nastier bugs being fixed are limited to non-premium accounts, some of them are rather visible.

### CODE REVIEW

**Comment by samuelclay** [comment]
Published as 4.7.0b1 on the beta channel.

**Comment by dosiecki** [comment]
This version has been perfectly stable, crash-wise.  Provided everyone is happy with the results of their testing and usage, I'd declare this ready to promote to Prod.

**Comment by samuelclay** [comment]
Could we somehow put that search bar at the top of every story list? But offset a bit so that it's hidden? You can scroll up to retrieve it, but it's just hanging out there. And keep the "Search" menu item.

**Comment by samuelclay** [comment]
Oh, I also hit this bug: http://stackoverflow.com/questions/26794862/failure-install-failed-update-incompatible. I got around it by just uninstalling the app and reinstalling, but do you ever run into this?

**Comment by dosiecki** [comment]
did you bump both the version number and version code between builds and
upgrades? this is mandatory from an OS perspective but not enforced by many
IDEs or build environments.

**Comment by dosiecki** [comment]
Fortunately, the Google app store has a sanity check that won't let you
upload a conflicting apk without a bump in versions.

**Comment by samuelclay** [comment]
I did bump both build number and version beforehand. Anyway, how hard would it be to get that search bar visible when scrolling up just a touch. (See the iOS app for a working example)

**Comment by dosiecki** [comment]
> I did bump both build number and version beforehand.

Hmm, did you switch from a release-level to a debug- or test- level build?  Or alternatively, switch which computer you did the signed build from? Trying to overwrite an app with a same-named one with different signing keys will also trigger that error (otherwise just about anyone could steal the data from within an app)

> Anyway, how hard would it be to get that search bar visible when scrolling up just a touch.

I would have to do some playing around.  This isn't a design element I have seen very often outside of about one app I can think of offhand. Swiping down from the head of a list is generally used to trigger a refresh on Android.  If we are looking to make the search function more noticable, it would be quite easy to put the search icon in the ActionBar when there is room, rather than having it buried in the menu.  This would match what about 50% of official Android apps do.

**Comment by samuelclay** [comment]
Ok, I'm game for the search icon. Do we have one already? Let me see... look for g_icn_search_black.png under media/img/icons/circular.

**Comment by dosiecki** [comment]
Will do.

**Pull request merged**
