### PR TITLE
Add Widget feature

### PR DESCRIPTION
**Pull request by caleb-allen**
Adds widget feature, as per #1161

### CODE REVIEW

**Comment by caleb-allen** [comment]
Working on the UI for the feed selection flow, and the styling for the widget. Will be ready to merge soon.

**Comment by samuelclay** [comment]
Looking forward to this!

**Comment by caleb-allen** [comment]
@samuelclay the feature is working, but I am having some issues with a synchronization race condition. Likely a few line fix, but finding where that needs to go has been challenging.

Where would you like my dev resources to be spent over coming days?

**Comment by samuelclay** [comment]
I think finishing up this feature would be a good use of time. Did you have any other issues in mind to work on before finishing this one?

**Comment by caleb-allen** [comment]
Sounds good. Was just seeing the activity on the missing image task, and wanted to make sure

**Comment by samuelclay** [comment]
Let's get to that one next, since it's a long standing issue.

**Comment by caleb-allen** [comment]
@samuelclay I believe this is ready

**Comment by samuelclay** [comment]
Nice! So how do I test this out? I did a cursory search but couldn't find where to add it.

**Comment by caleb-allen** [comment]
@samuelclay it will have to be added via your homescreen, should be a long press -> widgets I think

**Comment by caleb-allen** [comment]
Let me know your feedback

**Comment by samuelclay** [comment]
Firs thought, this should absolutely prioritize folders over feeds. name them (so they are in alphabetical order and folders are on top):

Folder: [Title]
Site: [Title]

**Comment by samuelclay** [comment]
Also, tapping stories does nothing but show the tap fade action.

**Comment by samuelclay** [comment]
Is it possible to add an icon before the folder/site title?

**Comment by samuelclay** [comment]
Tiny image previews would be nice as well. This is great stuff!

**Comment by caleb-allen** [comment]
Great feedback--tapping should work but I'll investigate that. As well as the icon, and folder feeds in the selections!

**Comment by caleb-allen** [comment]
> First thought, this should absolutely prioritize folders over feeds. name them (so they are in alphabetical order and folders are on top):
> 
> Folder: [Title]
> Site: [Title]

Is this what you have in mind?

Screenshot_1571112626

**Comment by samuelclay** [comment]
Yep, just remove the "Feed: " part.

**Pull request merged**
