### PR TITLE
Android: Beta Bugfixes

### PR DESCRIPTION
**Pull request by dosiecki**
Fixing a few bugs found in the latest beta and a few found by keen users on the forum.  Feature freezing from here forth so we can, with luck, take this one to Prod.

### CODE REVIEW

**Comment by samuelclay** [comment]
Just got the iOS app approved, so I'm ready to launch whenever you are.

**Comment by samuelclay** [comment]
Released as 5.2.0b4.

**Comment by dosiecki** [comment]
Are any beta users actually unlocked to use notifications other than we three devs?  I've had nothing in the way of feedback or crashes from the notification subsystem, and I would be curious to know if that is a false negative due to a lack of usage!

**Comment by samuelclay** [comment]
I haven't promoted it and because we're not sending Android notifications from the server, I can't track it either. I figure we'll fix any bugs as they come in, so long as the base system is there and works. Plus Android's quicker to fix than iOS.

**Comment by dosiecki** [comment]
Small set of fixes incoming.  Some of these are imperfect, but they are the best we can do with the limited testing data we've got so far.

**Pull request merged**
