### PR TITLE
Android: Options for Mark All Read

### PR DESCRIPTION
**Pull request by manderson23**
#856 and #866

### CODE REVIEW

**Comment by samuelclay** [comment]
Sweet, thanks Mark!

**Comment by samuelclay** [comment]
Looks great. I think this will roll into the 7.2 update. Daniel's working on something, although I'm not sure what. I would like to see saved story tags.

**Comment by dosiecki** [comment]
I was about 4/5 of the way through implementing saved story tag reading when I stopped to work on the hyperuser lag issue.  Will pick up on that as soon as we're out of emergency mode for the latter.

**Comment by samuelclay** [comment]
Excellent, thanks for jumping on that.

**Pull request merged**
