### PR TITLE
Android: Intelligence Training

### PR DESCRIPTION
**Pull request by dosiecki**
Big update to a single feature that hasn't seen much love in a few years - intel training.

Filled in the missing UI to allow full control of training at both a feed and story level from within the Android app.  All basic training functions should now be available.  Many small changes to make the app UI more closely follow the web UI for ease of use but still fit on smaller screens.  Some massive improvements to how quickly the UI responds to training actions.  Training actions now use the full defer-and-retry network manager for reliable use in poor reception or even offline.  And much more.

Ready for immediate release to Beta.

### CODE REVIEW

**Comment by samuelclay** [comment]
Whoa, this is incredible. Nicely done! Looks good, sending out to beta channel now as v7.0b1.

**Comment by samuelclay** [comment]
Also, I should note that I had another office break-in and they took my Nexus 5X. So I upgraded to a Pixel 1.

**Comment by dosiecki** [comment]
Well, in an attempt at optimism - my daily driver is a 5X and I don't have a Pixel, so at least we get more hardware test coverage!

**Comment by samuelclay** [comment]
How goes it? My iOS app has *finally* been approved after over a month of back-and-forth, so I'm ready to launch Infrequent Site Stories.

**Comment by dosiecki** [comment]
I haven't found any blocking bugs, just a few minor tweaks that can wait until a point release.  However, beta distribution/use is just starting to ramp up, so we wouldn't have received any crash reports yet.  That said, I have been training like crazy, and have had good luck.  If things look good for you, I'd be happy launching and keeping a careful eye on Prod.

**Comment by samuelclay** [comment]
Looks like the unread icons are missing. 

img_6c0213145797-1

**Comment by dosiecki** [comment]
Excellent catch. Will patch later tonight.

**Comment by samuelclay** [comment]
Also, you can normal case the folder title in the story titles view.

**Comment by samuelclay** [comment]
Hey I’d love to get this out the door Monday. Any chance you can have the
PR done tomorrow? I think because there’s so much to launch I’m going to
write three blog posts so nothing gets lost. Infrequent site stories,
iPhone X, and Android training.

On Dec 6, 2017, at 7:18 PM, Daniel <notifications@github.com> wrote:

Excellent catch. Will patch later tonight.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/samuelclay/NewsBlur/pull/1062#issuecomment-349850628>,
or mute the thread

**Comment by dosiecki** [comment]
> normal case the folder title in the story titles view

Should this be the case for all of the special folders?  Right now we use all caps consistently in both the folder list and at the heading for those associated story lists.  (not just Infrequent but also All Stories, All Social, Global, &c., &c.)

**Comment by samuelclay** [comment]
Yes, all folders. Headings are different than the story list titles.

**Pull request merged**
