### PR TITLE
Android: Beta Fixes

### PR DESCRIPTION
**Pull request by dosiecki**
A few fixes and small tweaks for the Beta release, including a particularly irksome crash reported by quite a few of our testers.

### CODE REVIEW

**Comment by dosiecki** [comment]
Also went ahead an added the new folder chooser fragment, since it is testing along nicely!

**Comment by samuelclay** [comment]
Excellent, looks good on both lollipop and marshmallow (I just upgraded my N7). Pushed out as beta3.

**Comment by dosiecki** [comment]
This has looked pretty stable over the last few days, so I think we ought to push it to production to alleviate the crashes being experienced by the ever-growing set of users on Android 6 even though it is a bit of a smaller release.

patch notes:
* full Android 6.0 compatibility
* bugfixes
* auto-open first unread story option
* richer send-to functionality
* choosing folders for feeds

**Comment by samuelclay** [comment]
I'll do that, but I'm going out of town starting Saturday. If we experience issues, we'll have to fix it tomorrow. But I'm OK with that, esp. since this is a patch release. Releasing now.

**Comment by samuelclay** [comment]
Released!

**Comment by dosiecki** [comment]
Excellent.  Will watch closely tonight and tomorrow AM.

**Pull request merged**
