### PR TITLE
TestCommit_AddSiteViewController_modification

### PR DESCRIPTION
**Pull request by TopCruiser**

### CODE REVIEW

**Comment by nriley** [comment]
@TopCruiser, what are these pull requests intended to accomplish? They are very confusing.

**Comment by samuelclay** [comment]
I hired him to squash all the ios8 warnings and move from ASI to AFN. It's an experiment to see if it's cost effective to handle these easy changes.

**Comment by nriley** [comment]
Thanks, just confused by the lack of commit messages, extraneous whitespace changes, etc. Good luck :-)

**Comment by samuelclay** [comment]
Looks like the whitespace changes are converting my tabs into spaces, which seems like the right thing to do. Github diffs look better now too.

**Pull request merged**
