### PR TITLE
Text importer

### PR DESCRIPTION
**Pull request by sv0**
fixed errors that happen when rss content has non-ASCII symbol or encoding is not utf-8.
e.g. cp1251 (windows cyrillic).

### CODE REVIEW

**Comment by samuelclay** [comment]
This is quite the change. How were you able to test it? Do you have NewsBlur running locally?

**Comment by samuelclay** [comment]
This is now launched. Everything's look good, so let me know if this changes a feed and preferably which feed has now been fixed.

**Comment by sv0** [comment]
Yes, I have NewsBlur running locally.
Errors happened while parsing these feeds:
http://24tv.ua/rss/all.xml
http://habrahabr.ru/rss/interesting/
http://www.pravda.com.ua/rss/

**Comment by samuelclay** [comment]
Thanks for this PR! Tweeted: https://twitter.com/newsblur/status/671827327999840256

**Pull request merged**
