### PR TITLE
Android: Bugfixes, Battery, Speed, and "Read Stories" View

### PR DESCRIPTION
**Pull request by dosiecki**
* A big change to the way we use cursors for story data that greatly reduces memory churn and CPU use
* More efficient and less wakeful story cleanup
* "Read stories" like the web UI has
* Some minor code cleanup
* A few bug fixes

### CODE REVIEW

**Comment by dosiecki** [comment]
Had an issue reported, freezing for more tests.

**Comment by dosiecki** [comment]
Sorted.

**Comment by samuelclay** [comment]
Is this ready for release or a beta build only right now?

**Comment by dosiecki** [comment]
I would suggest we Beta it for a while.  Lots of changes, but none of them are critical bugs.

**Comment by samuelclay** [comment]
Deployed as beta.

**Pull request merged**
