### PR TITLE
Android: Bugfixes

### PR DESCRIPTION
**Pull request by dosiecki**
Handfull of bugfixes for the current Beta including at least one critical fix.  Still holding back new features until this gets out to Prod.

### CODE REVIEW

**Comment by samuelclay** [comment]
Release as 8.0.0b4.

**Comment by dosiecki** [comment]
Beta is looking super clean.  I'm fine with promotion at any time.

**Comment by samuelclay** [comment]
Anything to add to this list?

* The grid view comes to Android. Each feed/folder has its own List view setting.
* New story pager has smooth transitions and fast updates.
* Fix for Twitter videos.
* Fix crash for viewing muted feeds.
* Long press links and images without tags.
* Fix issue where thumbnails and cached story imaged would be double downloaded.

**Comment by samuelclay** [comment]
Released to both the Play Store and updated the Amazon App Store.

**Comment by dosiecki** [comment]
> New story pager has smooth transitions and fast updates

The new pager isn't until the next release, this one just contains a ton of cleanup in preparation for it.  User-facing changes should be minimal.

> Fix issue where thumbnails and cached story imaged would be double downloaded

This bug never made it out of Beta, so shouldn't be relevant to Production users.

Other new stuff:
* Can scroll all the way past the last story (for marking-read while scrolling through story list)

Other bugfixes:
* Better login screen for very small devices
* Thumbnail loading much more memory and network efficient
* Story list position retained on rotate
* Many Android 8 compatibility fixes
* Colourblindness-friendly intel training

But mostly it is the fancy new story list with grid support and much, much smoother loading.

**Comment by samuelclay** [comment]
Blogged: http://blog.newsblur.com/post/176089041176/the-newsblur-android-app-hits-version-80-with-a

**Comment by nriley** [comment]
Looks great!

Blog post seems to have some issues with image aspect ratios - first
one is too tall, second one is too wide.

Nicholas

**Comment by samuelclay** [comment]
Yikes, thank you for letting me know. Looks like Tumblr rewrote my img tags when I hit preview one last time.

**Pull request merged**
